expected_clear_true = {'requests': [{'repeatCell': {'cell': {'userEnteredFormat': {'borders': {'bottom': {'color': {'blue': 0,
                                                                                              'green': 0,
                                                                                              'red': 0},
                                                                                    'style': 'SOLID',
                                                                                    'width': 1},
                                                                         'left': {'color': {'blue': 0,
                                                                                            'green': 0,
                                                                                            'red': 0},
                                                                                  'style': 'SOLID',
                                                                                  'width': 1},
                                                                         'right': {'color': {'blue': 0,
                                                                                             'green': 0,
                                                                                             'red': 0},
                                                                                   'style': 'SOLID',
                                                                                   'width': 1},
                                                                         'top': {'color': {'blue': 0,
                                                                                           'green': 0,
                                                                                           'red': 0},
                                                                                 'style': 'SOLID',
                                                                                 'width': 1}}}},
                              'fields': 'userEnteredFormat.borders',
                              'range': {'sheetId': 12345678}}}]}

expected_without_starts_ends = {'requests': [{'updateBorders': {'bottom': {'color': {'blue': 0,
                                                      'green': 0,
                                                      'red': 0},
                                            'style': 'SOLID',
                                            'width': 2},
                                 'left': {'color': {'blue': 0,
                                                    'green': 0,
                                                    'red': 0},
                                          'style': 'SOLID',
                                          'width': 2},
                                 'range': {'endColumnIndex': 30,
                                           'endRowIndex': 10000,
                                           'sheetId': 12345678,
                                           'startColumnIndex': 0,
                                           'startRowIndex': 0},
                                 'right': {'color': {'blue': 0,
                                                     'green': 0,
                                                     'red': 0},
                                           'style': 'SOLID',
                                           'width': 2},
                                 'top': {'color': {'blue': 0,
                                                   'green': 0,
                                                   'red': 0},
                                         'style': 'SOLID',
                                         'width': 2}}}]}

expected_rows_and_columns = {'requests': [{'updateBorders': {'bottom': {'color': {'blue': 0,
                                                      'green': 0,
                                                      'red': 0},
                                            'style': 'SOLID',
                                            'width': 2},
                                 'left': {'color': {'blue': 0,
                                                    'green': 0,
                                                    'red': 0},
                                          'style': 'SOLID',
                                          'width': 2},
                                 'range': {'endColumnIndex': 30,
                                           'endRowIndex': 10000,
                                           'sheetId': 12345678,
                                           'startColumnIndex': 0,
                                           'startRowIndex': 0},
                                 'right': {'color': {'blue': 0,
                                                     'green': 0,
                                                     'red': 0},
                                           'style': 'SOLID',
                                           'width': 2},
                                 'top': {'color': {'blue': 0,
                                                   'green': 0,
                                                   'red': 0},
                                         'style': 'SOLID',
                                         'width': 2}}}]}

expected_rows_only = {'requests': [{'updateBorders': {'bottom': {'color': {'blue': 0,
                                                      'green': 0,
                                                      'red': 0},
                                            'style': 'SOLID',
                                            'width': 2},
                                 'left': {'color': {'blue': 0,
                                                    'green': 0,
                                                    'red': 0},
                                          'style': 'SOLID',
                                          'width': 2},
                                 'range': {'endColumnIndex': 30,
                                           'endRowIndex': 5,
                                           'sheetId': 12345678,
                                           'startColumnIndex': 0,
                                           'startRowIndex': 1},
                                 'right': {'color': {'blue': 0,
                                                     'green': 0,
                                                     'red': 0},
                                           'style': 'SOLID',
                                           'width': 2},
                                 'top': {'color': {'blue': 0,
                                                   'green': 0,
                                                   'red': 0},
                                         'style': 'SOLID',
                                         'width': 2}}}]}

expected_start_row_and_column_only = {'requests': [{'updateBorders': {'bottom': {'color': {'blue': 0,
                                                      'green': 0,
                                                      'red': 0},
                                            'style': 'SOLID',
                                            'width': 2},
                                 'left': {'color': {'blue': 0,
                                                    'green': 0,
                                                    'red': 0},
                                          'style': 'SOLID',
                                          'width': 2},
                                 'range': {'endColumnIndex': 32,
                                           'endRowIndex': 10000,
                                           'sheetId': 12345678,
                                           'startColumnIndex': 2,
                                           'startRowIndex': 1},
                                 'right': {'color': {'blue': 0,
                                                     'green': 0,
                                                     'red': 0},
                                           'style': 'SOLID',
                                           'width': 2},
                                 'top': {'color': {'blue': 0,
                                                   'green': 0,
                                                   'red': 0},
                                         'style': 'SOLID',
                                         'width': 2}}}]}

expected_end_row_and_column_only = {'requests': [{'updateBorders': {'bottom': {'color': {'blue': 0,
                                                      'green': 0,
                                                      'red': 0},
                                            'style': 'SOLID',
                                            'width': 2},
                                 'left': {'color': {'blue': 0,
                                                    'green': 0,
                                                    'red': 0},
                                          'style': 'SOLID',
                                          'width': 2},
                                 'range': {'endColumnIndex': 5,
                                           'endRowIndex': 3,
                                           'sheetId': 12345678,
                                           'startColumnIndex': 0,
                                           'startRowIndex': 0},
                                 'right': {'color': {'blue': 0,
                                                     'green': 0,
                                                     'red': 0},
                                           'style': 'SOLID',
                                           'width': 2},
                                 'top': {'color': {'blue': 0,
                                                   'green': 0,
                                                   'red': 0},
                                         'style': 'SOLID',
                                         'width': 2}}}]}

expected_columns_only = {'requests': [{'updateBorders': {'bottom': {'color': {'blue': 0,
                                                      'green': 0,
                                                      'red': 0},
                                            'style': 'SOLID',
                                            'width': 2},
                                 'left': {'color': {'blue': 0,
                                                    'green': 0,
                                                    'red': 0},
                                          'style': 'SOLID',
                                          'width': 2},
                                 'range': {'endColumnIndex': 6,
                                           'endRowIndex': 10000,
                                           'sheetId': 12345678,
                                           'startColumnIndex': 2,
                                           'startRowIndex': 0},
                                 'right': {'color': {'blue': 0,
                                                     'green': 0,
                                                     'red': 0},
                                           'style': 'SOLID',
                                           'width': 2},
                                 'top': {'color': {'blue': 0,
                                                   'green': 0,
                                                   'red': 0},
                                         'style': 'SOLID',
                                         'width': 2}}}]}

expected_top_only = {'requests': [{'updateBorders': {'range': {'endColumnIndex': 30,
                                           'endRowIndex': 10000,
                                           'sheetId': 12345678,
                                           'startColumnIndex': 0,
                                           'startRowIndex': 0},
                                 'top': {'color': {'blue': 0,
                                                   'green': 0,
                                                   'red': 0},
                                         'style': 'SOLID',
                                         'width': 2}}}]}
