from json import load
from data.google.wb_initialize_spreadsheets.wb_initialize_spreadsheets import initialize_spreadsheets, \
    WildberriesSpreadSheet
from tests.test_GoogleSheetAPI.FakeService import GSA2, GSA
from tests.test_wb_initialize_spreadsheets.FakeWildberries import FakeWildberries
from config.constants import GOOGLE_SPREADSHEETS, GOOGLE_SPREADSHEETS_MIN, GOOGLE_SPREADSHEETS_OPT, GOOGLE_SHEETS_MANUAL

def fake_read_from_json(file):
    with open(file, 'r', encoding='utf8') as json_file:
        return load(json_file)


def test_initialize_spreadsheets(monkeypatch):

    monkeypatch.setattr('data.google.wb_initialize_spreadsheets.wb_initialize_spreadsheets.GOOGLE_SHEETS_MANUAL',
                        GOOGLE_SHEETS_MANUAL)
    monkeypatch.setattr('data.google.wb_initialize_spreadsheets.wb_initialize_spreadsheets.GoogleSheetAPI', GSA2)
    monkeypatch.setattr('data.google.wb_initialize_spreadsheets.wb_initialize_spreadsheets.GOOGLE_SPREADSHEETS_MIN',
                        GOOGLE_SPREADSHEETS_MIN)
    monkeypatch.setattr('data.google.wb_initialize_spreadsheets.wb_initialize_spreadsheets.GOOGLE_SPREADSHEETS_OPT',
                        GOOGLE_SPREADSHEETS_OPT)
    monkeypatch.setattr('data.google.wb_initialize_spreadsheets.wb_initialize_spreadsheets.GOOGLE_SPREADSHEETS',
                        GOOGLE_SPREADSHEETS)
    monkeypatch.setattr('data.google.wb_initialize_spreadsheets.wb_initialize_spreadsheets.read_from_json',
                        fake_read_from_json)

    monkeypatch.setattr('data.google.wb_initialize_spreadsheets.wb_initialize_spreadsheets.WildberriesSpreadSheet', FakeWildberries)
    expected_1 = {'Wildberries': {'id': 0,'sheets': {'day': {'id': 0,'title': 'День','title_db': 'Ежедневный отчет'}, 'dynamic_count': {'id': 0,'title': 'Динамика (шт)','title_db': 'Динамика заказов ''поартикульно, шт'},'dynamic_rub': {'id': 0,'title': 'Динамика (руб)','title_db': 'Динамика заказов ''поартикульно, руб'},'month': {'id': 0,'title': 'Месяц','title_db': 'Ежедневный отчет за месяц'},'orders_all_categories': {'id': 0,'title': 'Заказы (все ''категории)','title_db': 'Динамика ''заказов по ''всем ''категориям, ''руб'},'plan': {'id': 0,'title': 'План','title_db': 'План'},'week': {'id': 0,'title': 'Неделя','title_db': 'Ежедневный отчет за неделю'}},'title': 'Wildberries'}}
    assert initialize_spreadsheets(1) == expected_1

    expected_2 = {'Wildberries': {'id': 0, 'sheets': {'day': {'id': 0, 'title': 'День', 'title_db': 'Ежедневный отчет'}, 'dynamic_count': {'id': 0, 'title': 'Динамика (шт)', 'title_db': 'Динамика заказов ' 'поартикульно, шт'}, 'dynamic_rub': {'id': 0, 'title': 'Динамика (руб)', 'title_db': 'Динамика заказов ' 'поартикульно, руб'}, 'month': {'id': 0, 'title': 'Месяц', 'title_db': 'Ежедневный отчет за месяц'}, 'orders_all': {'id': 0, 'title': 'Заказы (все)', 'title_db': 'Динамика заказов по ' 'выбранным категориям, ' 'руб'}, 'orders_all_categories': {'id': 0, 'title': 'Заказы (все ' 'категории)', 'title_db': 'Динамика ' 'заказов по ' 'всем ' 'категориям, ' 'руб'}, 'plan': {'id': 0, 'title': 'План', 'title_db': 'План'}, 'region_remains': {'id': 0, 'title': 'Остатки Регионы', 'title_db': 'Отчет по ' 'региональным ' 'остаткам'}, 'remains': {'id': 0, 'title': 'Остатки', 'title_db': 'Отчет по остаткам на ' 'складах ВБ'}, 'top500': {'id': 0, 'title': 'Топ-500', 'title_db': 'Категорийная динамика ' 'заказов по выбранным sku, ' 'руб'}, 'week': {'id': 0, 'title': 'Неделя', 'title_db': 'Ежедневный отчет за неделю'}}, 'title': 'Wildberries'}, 'Wildberries 2': {'id': 0, 'sheets': {'abc_article_report': {'id': 0, 'title': 'ABC (арт)', 'title_db': 'ABC-анализ ' 'по ' 'артикулам'}, 'abc_report': {'id': 0, 'title': 'ABC', 'title_db': 'ABC-анализ'}, 'abc_subject_report': {'id': 0, 'title': 'ABC (предмет)', 'title_db': 'ABC-анализ ' 'по ' 'предметам'}, 'dispatch': {'id': 0, 'title': 'Отгрузка', 'title_db': 'Отчет по отгрузке'}, 'dynamic_categories': {'id': 0, 'title': 'Динамика ' '(категории)', 'title_db': 'Ежечасная ' 'динамика ' 'заказов по ' 'категориям, ' 'руб'}, 'feedbacks': {'id': 0, 'title': 'Отзывы', 'title_db': 'Отчет по отзывам'}, 'op_ev_day': {'id': 0, 'title': 'ОП ежедн', 'title_db': 'Ежедневный отчет по ' 'ОП, сводная'}, 'percent_article': {'id': 0, 'title': 'Выкуп (артикул)', 'title_db': 'Процент выкупа ' 'по артикулу'}, 'percent_color': {'id': 0, 'title': 'Выкуп (цвет)', 'title_db': 'Процент выкупа по ' 'цвету'}, 'percent_size': {'id': 0, 'title': 'Выкуп (размер)', 'title_db': 'Процент выкупа по ' 'размеру'}, 'percent_subject': {'id': 0, 'title': 'Выкуп (предмет)', 'title_db': 'Процент выкупа ' 'по предмету'}, 'profit': {'id': 0, 'title': 'ОП подробная', 'title_db': 'Ежедневный отчет по ОП, ' 'полная'}, 'profitability': {'id': 0, 'title': 'Рентабельность ' '(титул)', 'title_db': 'Отчет по ' 'рентабельности - ' 'титул'}, 'profitability_color': {'id': 0, 'title': 'Рентабельность ' '(цвет)', 'title_db': 'Отчет по ' 'рентабельности ' 'по sku'}, 'profitability_object': {'id': 0, 'title': 'Рентабельность ' '(предмет)', 'title_db': 'Отчет по ' 'рентабельности ' 'по ' 'предметам'}}, 'title': 'Wildberries 2'}, 'Wildberries Log PC': {'id': 0, 'sheets': {'logistics': {'id': 0, 'title': 'Логистика', 'title_db': 'Логистика'}, 'prime_cost': {'id': 0, 'title': 'Себестоимость', 'title_db': 'Себестоимость'}}, 'title': 'Wildberries Log PC'}}
    assert initialize_spreadsheets(2) == expected_2

    expected_3 = {'Wildberries': {'id': 0, 'title': 'Wildberries', 'sheets': {'day': {'id': 0, 'title': 'День', 'title_db': 'Ежедневный отчет'}, 'week': {'id': 0, 'title': 'Неделя', 'title_db': 'Ежедневный отчет за неделю'}, 'month': {'id': 0, 'title': 'Месяц', 'title_db': 'Ежедневный отчет за месяц'}, 'plan': {'id': 0, 'title': 'План', 'title_db': 'План'}, 'dynamic_count': {'id': 0, 'title': 'Динамика (шт)', 'title_db': 'Динамика заказов поартикульно'}, 'dynamic_rub': {'id': 0, 'title': 'Динамика (руб)', 'title_db': 'Динамика заказов поартикульно'}, 'orders_all_categories': {'id': 0, 'title': 'Заказы (все категории)', 'title_db': 'Динамика заказов по всем категориям'}, 'orders_all': {'id': 0, 'title': 'Заказы (все)', 'title_db': 'Динамика заказов по выбранным категориям'}, 'remains': {'id': 0, 'title': 'Остатки', 'title_db': 'Отчет по остаткам на складах ВБ'}, 'region_remains': {'id': 0, 'title': 'Остатки Регионы', 'title_db': 'Отчет по региональным остаткам'}, 'top500': {'id': 0, 'title': 'Топ-500', 'title_db': 'Категорийная динамика заказов по выбранным sku'}}}, 'Wildberries 2': {'id': 0, 'title': 'Wildberries 2', 'sheets': {'feedbacks': {'id': 0, 'title': 'Отзывы', 'title_db': 'Отчет по отзывам'}, 'dispatch': {'id': 0, 'title': 'Отгрузка', 'title_db': 'Отчет по отгрузке'}, 'dynamic_categories': {'id': 0, 'title': 'Динамика (категории)', 'title_db': 'Ежечасная динамика заказов по категориям'}, 'profit': {'id': 0, 'title': 'ОП подробная', 'title_db': 'Ежедневный отчет по ОП'}, 'op_ev_day': {'id': 0, 'title': 'ОП ежедн', 'title_db': 'Ежедневный отчет по ОП, сводная'}, 'profitability': {'id': 0, 'title': 'Рентабельность (титул)', 'title_db': 'Отчет по рентабельности'}, 'profitability_color': {'id': 0, 'title': 'Рентабельность (цвет)', 'title_db': 'Отчет по рентабельности по sku'}, 'profitability_object': {'id': 0, 'title': 'Рентабельность (предмет)', 'title_db': 'Отчет по рентабельности по предметам'}, 'percent_color': {'id': 0, 'title': 'Выкуп (цвет)', 'title_db': 'Процент выкупа'}, 'percent_size': {'id': 0, 'title': 'Выкуп (размер)', 'title_db': 'Процент выкупа по размеру'}, 'percent_article': {'id': 0, 'title': 'Выкуп (артикул)', 'title_db': 'Процент выкупа по артикулу'}, 'percent_subject': {'id': 0, 'title': 'Выкуп (предмет)', 'title_db': 'Процент выкупа по предмету'}, 'abc_report': {'id': 0, 'title': 'ABC', 'title_db': 'ABC-анализ'}, 'abc_article_report': {'id': 0, 'title': 'ABC (арт)', 'title_db': 'ABC-анализ по артикулам'}, 'abc_subject_report': {'id': 0, 'title': 'ABC (предмет)', 'title_db': 'ABC-анализ по предметам'}, 'liquidity': {'id': 0, 'title': 'Ликвидность', 'title_db': 'Фирменный отчет MarketData'}}}, 'Wildberries Log PC': {'id': 0, 'title': 'Wildberries Log PC', 'sheets': {'logistics': {'id': 0, 'title': 'Логистика', 'title_db': 'Логистика'}, 'prime_cost': {'id': 0, 'title': 'Себестоимость', 'title_db': 'Себестоимость'}}}}
    assert initialize_spreadsheets(3) == expected_3

    assert initialize_spreadsheets(4) == expected_3

    assert initialize_spreadsheets(5) == expected_3
