from data.utils.functions import html_color_to_json

RED_DEEP = html_color_to_json('#e90c0c')
YELLOW = html_color_to_json('#e8be0c')
GREEN_DEEP = html_color_to_json('#3bcd37')
GRAY = html_color_to_json('#d9d9d9')
GRAY_HEADERS = html_color_to_json('#bdbdbd')
RED_LIGHT = html_color_to_json('#f4cccc')
GREEN_LIGHT = html_color_to_json('#b7e1cd')
WHITE = html_color_to_json('#ffffff')
BLACK = html_color_to_json('#000000')
BLUE_LIGHT = html_color_to_json('#d9edf2')
SKIN_LIGHT = html_color_to_json('fce5cd')
PURPLE_LIGHT = html_color_to_json('#ece3ee')
PINK_LIGHT = html_color_to_json('#ead1dc')
SKIN = html_color_to_json('#f9cb9c')
SALAD = html_color_to_json('#cce0bb')
SKIN_SUPER_LIGHT = html_color_to_json('#ddd9c4')
OVERALL_CELL_HTML_COLOR = html_color_to_json('#c0bcf5')
